name: execution_queue
description: Transaction like execution queue to synchronize asynchronous jobs.
version: 1.1.0+1
homepage: https://github.com/fosscom/execution_queue

environment:
    sdk: '>=2.8.1 <3.0.0'



dev_dependencies:
  test: any
  pedantic: ^1.9.0
  collection: any