name: execution_queue
description: Transaction like execution queue to synchronize asynchronous jobs.
version: 0.0.1
author: Team netz.chat <dev@netz.chat>
homepage: https://github.com/netz-chat/execution_queue
environment:
    sdk: ">=1.19.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: