name: execution_queue
description: Transaction like execution queue to synchronize asynchronous jobs.
version: 1.2.0
homepage: https://github.com/marioreggiori/execution_queue.dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: any
