name: execution_queue
description: Transaction like execution queue to synchronize asynchronous jobs.
version: 1.0.3
homepage: https://github.com/netz-chat/execution_queue
environment:
    sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  test: any
